commonConfig:
  prefix: "gronosq"
  batchSize: 100
kafkaConfig:
  brokers: "localhost"
  topic: "ktopic-gronosq"
  group: "kgroup-gronosq"
zooKeeperConfig:
  servers: "localhost:2181"
  zkPath: "/ha-nodes"
redisConfig:
  servers: "localhost:6379"
  password: ""
  database: 0